GCC = gcc -Wall -Werror -Wextra

compile:	rush01.c ft_algorithm.c ft_checker.c ft_checker_functions.c ft_clues.c ft_display.c ft_functions.c ft_iscol.c ft_isrow.c ft_split.c ft_zero.c ft_arr_create_delete.c
	$(GCC) rush01.c ft_algorithm.c ft_checker.c ft_checker_functions.c ft_clues.c ft_display.c ft_functions.c ft_iscol.c ft_isrow.c ft_split.c ft_zero.c ft_arr_create_delete.c -o run
	./run "4 3 2 1 1 2 2 2 4 3 2 1 1 2 2 2" | cat -e
